# Generated by Django 4.1.7 on 2023-03-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshopmanagementapp', '0002_worker_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='worker',
            new_name='workers',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='user_name',
            new_name='username',
        ),
    ]
