# Generated by Django 4.1.7 on 2023-03-22 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshopmanagementapp', '0003_rename_worker_workers_rename_name_manager_username_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='workers',
            new_name='workerss',
        ),
    ]
