# Generated by Django 4.1.7 on 2023-03-22 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshopmanagementapp', '0004_rename_workers_workerss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='workerss',
            new_name='worker',
        ),
    ]
