# Generated by Django 4.1.7 on 2023-03-22 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshopmanagementapp', '0005_rename_workerss_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='customer',
        ),
    ]
