# Generated by Django 4.1.7 on 2023-03-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshopmanagementapp', '0006_remove_manager_customer_remove_worker_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='is_customer',
            new_name='is_manager',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='is_manage',
            new_name='is_worker',
        ),
    ]
